service: cm-clockin-btn 

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  timeout: 300
  profile: cm-hirata.kei
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::cm-hiratakei-hogehoge*"

package:
  exclude:
    - .venv/**

functions:
  clockin:
    handler: handler.handler
    layers:
      - {Ref: HeadlessDashchromiumLambdaLayer}

layers:
  headless-chromium:
    path: layers/headless-chromium
    compatibleRuntimes:
      - python3.6
    allowedAccounts:
      - '*'
plugins:
  - serverless-python-requirements
