service: cm-clockin-btn 

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  timeout: 300
  profile: cm-clockin-button
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: !Join [ "", [ !GetAtt SSBackup.Arn, "/*" ] ]

resources:
  Resources:
    SSBackup:
      Type: AWS::S3::Bucket

package:
  exclude:
    - .venv/**

functions:
  clockin:
    handler: handler.handler
    layers:
      - {Ref: HeadlessDashchromiumLambdaLayer}
    environment:
      BACKUP_BUCKET: !Ref SSBackup

layers:
  headless-chromium:
    path: layers/headless-chromium
    compatibleRuntimes:
      - python3.6
    allowedAccounts:
      - '*'
plugins:
  - serverless-python-requirements
