service: cm-workin-btn 

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  profile: cm-hirata.kei

package:
  exclude:
    - .venv/**

functions:
  clockin:
    handler: handler.clockin_handler
    layers:
      - {Ref: HeadlessDashchromiumLambdaLayer}

layers:
  headless-chromium:
    path: layers/headless-chromium
    compatibleRuntimes:
      - python3.6
    allowedAccounts:
      - '*'